
## 실습 과제1: NumPy를 활용한 행렬 변형 실습

In [3]:
import numpy as np

### 문제 1: 난수 행렬 생성

N = 6과 M = 5로 설정하고, 0과 1 사이의 난수를 사용하여 (N, M) 형태의 행렬 A를 생성하세요.
힌트: np.random.rand() 함수를 사용하세요.

In [20]:
N = 6
M = 5
A = np.random.rand(N,M)
print(A)

[[0.04787875 0.3338188  0.12930366 0.85721628 0.91388626]
 [0.21178782 0.92053331 0.72158913 0.57760083 0.0295084 ]
 [0.04673364 0.43894845 0.93809309 0.90542129 0.47464001]
 [0.5841081  0.76069694 0.43401571 0.50753669 0.09691687]
 [0.40515067 0.00094645 0.22266682 0.27235799 0.38496533]
 [0.6454903  0.3021283  0.82553278 0.38747355 0.51158155]]


### 문제 2: 새로운 축 추가

행렬 A에 np.newaxis를 사용하여 새로운 축을 추가하고, 결과를 B에 저장하세요. B의 형태는 (N, 1, M)이 되어야 합니다.

In [21]:
B = A[:,np.newaxis,:]
print(B)
print("B의 형태:", B.shape)

[[[0.04787875 0.3338188  0.12930366 0.85721628 0.91388626]]

 [[0.21178782 0.92053331 0.72158913 0.57760083 0.0295084 ]]

 [[0.04673364 0.43894845 0.93809309 0.90542129 0.47464001]]

 [[0.5841081  0.76069694 0.43401571 0.50753669 0.09691687]]

 [[0.40515067 0.00094645 0.22266682 0.27235799 0.38496533]]

 [[0.6454903  0.3021283  0.82553278 0.38747355 0.51158155]]]
B의 형태: (6, 1, 5)


### 문제 3: 슬라이싱을 이용한 특정 요소 변경

행렬 B에서 세 번째 행의 모든 열을 슬라이싱하여 값을 0.3으로 변경하세요.

In [22]:
B[3][::]=0.3
print(B)

[[[0.04787875 0.3338188  0.12930366 0.85721628 0.91388626]]

 [[0.21178782 0.92053331 0.72158913 0.57760083 0.0295084 ]]

 [[0.04673364 0.43894845 0.93809309 0.90542129 0.47464001]]

 [[0.3        0.3        0.3        0.3        0.3       ]]

 [[0.40515067 0.00094645 0.22266682 0.27235799 0.38496533]]

 [[0.6454903  0.3021283  0.82553278 0.38747355 0.51158155]]]



### 문제 4: 축 위치를 다르게 설정하여 새로운 행렬 생성

np.newaxis를 사용하여 A의 형태를 (1, N, M)로 변형한 결과를 C에 저장하고, (N, M, 1)로 변형한 결과를 D에 저장하세요. 각 행렬의 형태를 출력하여 확인하세요.


In [25]:
C = A[np.newaxis,:,:]
print("C의 형태:", C.shape)
print("행렬 C : ")
print(C)

D = A[:,:,np.newaxis]
print("D의 형태:", D.shape)
print("행렬 D : ")
print(D)

C의 형태: (1, 6, 5)
행렬 C : 
[[[0.04787875 0.3338188  0.12930366 0.85721628 0.91388626]
  [0.21178782 0.92053331 0.72158913 0.57760083 0.0295084 ]
  [0.04673364 0.43894845 0.93809309 0.90542129 0.47464001]
  [0.8        0.8        0.8        0.8        0.8       ]
  [0.8        0.8        0.8        0.8        0.8       ]
  [0.8        0.8        0.8        0.8        0.8       ]]]
D의 형태: (6, 5, 1)
행렬 D : 
[[[0.04787875]
  [0.3338188 ]
  [0.12930366]
  [0.85721628]
  [0.91388626]]

 [[0.21178782]
  [0.92053331]
  [0.72158913]
  [0.57760083]
  [0.0295084 ]]

 [[0.04673364]
  [0.43894845]
  [0.93809309]
  [0.90542129]
  [0.47464001]]

 [[0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]]

 [[0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]]

 [[0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]]]



### 문제 5: 슬라이싱을 통해 부분 행렬 변경

행렬 D에서 마지막 세 행의 모든 요소를 0.8로 변경하세요.

In [24]:
D[-3:][::] = 0.8
print("행렬 D : ")
print(D)

행렬 D : 
[[[0.04787875]
  [0.3338188 ]
  [0.12930366]
  [0.85721628]
  [0.91388626]]

 [[0.21178782]
  [0.92053331]
  [0.72158913]
  [0.57760083]
  [0.0295084 ]]

 [[0.04673364]
  [0.43894845]
  [0.93809309]
  [0.90542129]
  [0.47464001]]

 [[0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]]

 [[0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]]

 [[0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]]]
