In [1]:
len?

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

In [2]:
l = [1,2,3,4,5]

In [3]:
print(l)

[1, 2, 3, 4, 5]


In [1]:
%pwd

'C:\\workspace_ptyhon\\jupyter_notebook'

In [2]:
%ls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 58B3-92B1

 C:\workspace_ptyhon\jupyter_notebook 디렉터리

2024-11-12  오전 10:50    <DIR>          .
2024-11-12  오전 10:50    <DIR>          ..
2024-11-12  오전 10:50    <DIR>          .ipynb_checkpoints
2024-11-12  오전 10:50             2,179 AIProg_chap01.ipynb
2024-11-12  오전 10:50               147 myscript.py
               2개 파일               2,326 바이트
               3개 디렉터리  420,306,644,992 바이트 남음


In [3]:
%run myscript.py

1 의 제곱은  1
2 의 제곱은  4
3 의 제곱은  9


In [1]:
import numpy as np

In [2]:
import array
L =list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
import numpy as np

In [5]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [7]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [8]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [9]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.arange(0,20,2)       ##기억할 것

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [18]:
np.random.randint(0,10,(10,10))

array([[8, 8, 9, 7, 4, 4, 7, 6, 4, 5],
       [0, 8, 6, 3, 5, 1, 2, 6, 7, 3],
       [9, 6, 6, 6, 5, 8, 1, 6, 9, 3],
       [0, 5, 2, 0, 5, 9, 1, 8, 8, 2],
       [5, 8, 3, 8, 2, 3, 0, 7, 0, 8],
       [2, 2, 9, 8, 5, 3, 7, 3, 7, 3],
       [9, 1, 0, 4, 3, 3, 3, 6, 9, 5],
       [2, 0, 5, 8, 4, 7, 2, 2, 9, 1],
       [0, 4, 7, 0, 3, 6, 3, 8, 9, 3],
       [7, 7, 6, 3, 2, 4, 0, 4, 0, 6]], dtype=int32)

In [19]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)          #1차원배열
x2 = np.random.randint(10, size=(3,4))      #2차원배열
x3 = np.random.randint(10, size=(3,4,5))    #3차원배열

In [22]:
print("x1 is \n", x1)
print("x2 is \n", x2)
print("x3 is \n", x3)

x1 is 
 [5 0 3 3 7 9]
x2 is 
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
x3 is 
 [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [31]:
grid = np.arange(1,10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
grid = grid.reshape(3,3)       #2차원 배열의 크기로 만들어주기 때문에 원소 갯수가 맞아야함
grid                           #(3,2) 로 할 경우 에러!

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
grid.reshape(1,9)       #(9,1)과의 차이?

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])