### BroadCasting

In [1]:
import numpy as np

같은 크기의 배열에서 이항 연산은 배열의 요소 단위로 수행됨

In [2]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

브로드캐스팅을 사용하면 서로 다른 크기의 배열에서 수행할 수 있음

In [3]:
a + 5

array([5, 6, 7])

예시1)

In [4]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

예시2)

In [12]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
print(a)
print(b)

[[0]
 [1]
 [2]]
[0 1 2]


In [13]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

예시3) 호환되지 않을 경우 -> 명시적으로 오른쪽 덧붙이기 

In [ ]:
M = np.ones((3, 2))
a = np.arange(3)

#M + a   #호환되지 않아 오류 발생

a[:, np.newaxis].shape

(3, 1)

In [17]:
M + a[:, np.newaxis]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])